In [1]:
import os
os.listdir('data')

['input_2022-12-03.txt',
 'input_2022-12-04.txt',
 'input_2022_12_02.txt',
 'input_2022_12_01.txt']

In [1]:
with open('data/input_2022-12-04.txt') as f:
    text = [line.strip('\n').split(',') for line in f.readlines()]
    
import numpy as np

assignments = np.asarray([[y.split('-') for y in x] for x in text], dtype = int)

assignments.shape
assignments[0:5,:,:]

array([[[60, 60],
        [45, 60]],

       [[36, 57],
        [ 7, 36]],

       [[ 2, 32],
        [ 1, 55]],

       [[ 1, 30],
        [ 6, 75]],

       [[12, 13],
        [13, 90]]])

In [45]:
for row in assignments[0:5]:
    
    print(row)
   # print(row[0][0])
    print('First', row[0,0], row[0, 1])
    print('Second:', row[1,0], row[1, 1])
    
    if (row[0][0] <= row[1][0]) & (row[0][1] >= row[1][1]):
        print(1)
    elif (row[1][0] <= row[0][0]) & (row[1][1] >= row[0][1]):
        print(1)
    else:
        print(0)

[[60 60]
 [45 60]]
First 60 60
Second: 45 60
1
[[36 57]
 [ 7 36]]
First 36 57
Second: 7 36
0
[[ 2 32]
 [ 1 55]]
First 2 32
Second: 1 55
1
[[ 1 30]
 [ 6 75]]
First 1 30
Second: 6 75
0
[[12 13]
 [13 90]]
First 12 13
Second: 13 90
0


#### Function to Check Overlap

In [44]:
def check_overlap(a, b):
    
        
    if (a[0] <= b[0]) & (a[1] >= b[1]):
        return 1
    elif (b[0] <= a[0]) & (b[1] >= a[1]):
        return 1
    else:
        return 0
    
    
print(check_overlap([1, 10], [5, 5]))
print(check_overlap([3, 4], [2, 5]))
print(check_overlap([1, 4], [2, 5]))
print(check_overlap([3, 7], [2, 5]))
print(check_overlap([3, 7], [5, 10]))
print(check_overlap([3, 7], [1, 6]))

1
1
0
0
0
0


In [49]:
check = [check_overlap(pairs[0], pairs[1]) for pairs in assignments]
check[0:5]

[1, 0, 1, 0, 0]

In [50]:
np.sum(check)

431

## Part 2:

In [54]:
for row in assignments[0:20]:
    
    print(row)
   # print(row[0][0])
    print('First', row[0,0], row[0, 1])
    print('Second:', row[1,0], row[1, 1])
    
    if (row[0][1] < row[1][0]):
        print(0)
    elif (row[0][0] > row[1][1]):
        print(0)
    else:
        print(1)

[[60 60]
 [45 60]]
First 60 60
Second: 45 60
1
[[36 57]
 [ 7 36]]
First 36 57
Second: 7 36
1
[[ 2 32]
 [ 1 55]]
First 2 32
Second: 1 55
1
[[ 1 30]
 [ 6 75]]
First 1 30
Second: 6 75
1
[[12 13]
 [13 90]]
First 12 13
Second: 13 90
1
[[48 98]
 [48 98]]
First 48 98
Second: 48 98
1
[[29 29]
 [29 51]]
First 29 29
Second: 29 51
1
[[ 5  8]
 [ 7 92]]
First 5 8
Second: 7 92
1
[[39 91]
 [38 90]]
First 39 91
Second: 38 90
1
[[ 3 41]
 [16 86]]
First 3 41
Second: 16 86
1
[[64 64]
 [65 95]]
First 64 64
Second: 65 95
0
[[ 4  4]
 [ 5 96]]
First 4 4
Second: 5 96
0
[[ 8 43]
 [ 9 22]]
First 8 43
Second: 9 22
1
[[82 88]
 [20 46]]
First 82 88
Second: 20 46
0
[[19 20]
 [ 9 20]]
First 19 20
Second: 9 20
1
[[73 74]
 [10 74]]
First 73 74
Second: 10 74
1
[[23 29]
 [22 23]]
First 23 29
Second: 22 23
1
[[21 82]
 [22 83]]
First 21 82
Second: 22 83
1
[[36 36]
 [36 84]]
First 36 36
Second: 36 84
1
[[34 35]
 [35 74]]
First 34 35
Second: 35 74
1


In [57]:
def check_overlap_any(a, b):
    
        
    if (a[1] < b[0]):
        return 0
    elif (a[0] > b[1]):
        return 0
    else:
        return 1
    
print(check_overlap_any([34, 35], [35, 74]))
print(check_overlap_any([20, 46], [82, 88]))
    

1
0


In [61]:
check2 = [check_overlap_any(pairs[0], pairs[1]) for pairs in assignments]
check2[0:5]

[1, 1, 1, 1, 1]

In [62]:
np.sum(check2)

823