## Read Crates

In [321]:
count = 0
text = []
with open('data/input_2022-12-05.txt') as f:
    while count < 9:
        count += 1
        
        line =f.readline()
        
        if not line:
            break
        else:
            text.append(line.strip('\n').replace('[', ' ').replace(']',' '))
      

            
#print(text)

import numpy as np
#print(text[0])

#text_elem = [[elem for elem in row] for row in text[0]]
#text_elem


text_rows = [[elem for elem in row] for row in text]
text_array = np.asarray(text_rows, dtype ='U1').T

#text_idx = text_array[:,9] != ' '

#text_array[text_idx, 0:8]

crate_list = [i[i != ' '][::-1] for i in text_array[text_idx, 0:8]]

for crate in crate_list:
    print(crate)

['L' 'N' 'W' 'T' 'D']
['C' 'P' 'H']
['W' 'P' 'H' 'N' 'D' 'G' 'M' 'J']
['C' 'W' 'S' 'N' 'T' 'Q' 'L']
['P' 'H' 'C' 'N']
['T' 'H' 'N' 'D' 'M' 'W' 'Q' 'B']
['M' 'B' 'R' 'J' 'G' 'S' 'L']
['Z' 'N' 'W' 'G' 'V' 'B' 'R' 'T']
['W' 'G' 'D' 'N' 'P' 'L']


## Read Move Instructions

In [322]:
moves = []
count = 0
with open('data/input_2022-12-05.txt') as f:
    
    lines = f.readlines()
    for i,line in enumerate(lines):
        if i > 9:
            moves.append(line.strip('\n'))
moves[0:5]

['move 6 from 6 to 5',
 'move 2 from 5 to 9',
 'move 8 from 9 to 1',
 'move 3 from 5 to 4',
 'move 9 from 1 to 8']

#### Clean each move instruction

In [323]:
def clean_moves(step):
    clean_step = step.replace('move', '').replace('from', ',').replace('to',',').replace(' ','')
    return clean_step.split(',')

move_list= np.asarray([clean_moves(step) for step in moves], dtype = int)
move_list[0:5]

array([[6, 6, 5],
       [2, 5, 9],
       [8, 9, 1],
       [3, 5, 4],
       [9, 1, 8]])

In [467]:
def move_cargo( n, move_from, move_to, cargo_list = crate_list):

    new_cargo_list = cargo_list
    
    cargo_to_move = cargo_list[move_from-1][-n::]
   
    new_cargo_list[move_from-1]= cargo_list[move_from-1][0:-n]
    new_cargo_list[move_to-1] = np.concatenate(( cargo_list[move_to - 1], cargo_to_move[::-1]))
    
    return(new_cargo_list)




In [468]:
crate_list = [i[i != ' '][::-1] for i in text_array[text_idx, 0:8]]

print('Start Position: \n')
for crates in crate_list:
    print(crates)
    
for move in move_list:
    move_cargo(move[0], move[1], move[2], crate_list);
    
print('\nEnd Position: \n')
for crate in crate_list:
    print(crate)
    
print('\nTop Crates\n')
''.join([crate[-1] for crate in crate_list])


#TWSGQHNHL'

Start Position: 

['L' 'N' 'W' 'T' 'D']
['C' 'P' 'H']
['W' 'P' 'H' 'N' 'D' 'G' 'M' 'J']
['C' 'W' 'S' 'N' 'T' 'Q' 'L']
['P' 'H' 'C' 'N']
['T' 'H' 'N' 'D' 'M' 'W' 'Q' 'B']
['M' 'B' 'R' 'J' 'G' 'S' 'L']
['Z' 'N' 'W' 'G' 'V' 'B' 'R' 'T']
['W' 'G' 'D' 'N' 'P' 'L']

End Position: 

['T']
['W']
['W' 'J' 'N' 'S']
['N' 'M' 'V' 'R' 'D' 'N' 'H' 'Z' 'T' 'P' 'J' 'G']
['L' 'C' 'Q']
['M' 'W' 'B' 'W' 'D' 'P' 'H']
['S' 'P' 'G' 'N' 'C' 'G' 'M' 'H' 'N' 'L' 'W' 'T' 'N' 'D' 'T' 'W' 'G' 'R'
 'N']
['Q' 'D' 'H']
['P' 'B' 'B' 'L' 'C' 'L']

Top Crates



'TWSGQHNHL'

## Part 2

In [472]:
def move_cargo_multi( n, move_from, move_to, cargo_list = crate_list):

    new_cargo_list = cargo_list
    
    cargo_to_move = cargo_list[move_from-1][-n::]
   # print('Cargo to move', cargo_to_move)

    new_cargo_list[move_from-1] = cargo_list[move_from-1][0:-n]
    
    new_cargo_list[move_to-1] = np.concatenate(( cargo_list[move_to - 1], cargo_to_move))
    
    return(new_cargo_list)



## Test

    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 

move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2

In [470]:
test_list = [np.asarray(['Z', 'N']), np.asarray(['M', 'C', 'D']), np.asarray(['P'])]

test_list
move_cargo_multi(1,2,1, test_list)
move_cargo_multi(3,1,3, test_list)
move_cargo_multi(2,2,1, test_list)
move_cargo_multi(1,1,2, test_list)


for cargo in test_list:
    print(cargo)

Cargo to move ['D']
Cargo to move ['Z' 'N' 'D']
Cargo to move ['M' 'C']
Cargo to move ['C']
['M']
['C']
['P' 'Z' 'N' 'D']


In [473]:
crate_list = [i[i != ' '][::-1] for i in text_array[text_idx, 0:8]]

print('Start Position: \n')
for crates in crate_list:
    print(crates)
    
for move in move_list:
    move_cargo_multi(move[0], move[1], move[2], crate_list);
    
print('\nEnd Position: \n')
for crate in crate_list:
    print(crate)
    
print('\nTop Crates\n')


''.join([crate[-1] for crate in crate_list])

Start Position: 

['L' 'N' 'W' 'T' 'D']
['C' 'P' 'H']
['W' 'P' 'H' 'N' 'D' 'G' 'M' 'J']
['C' 'W' 'S' 'N' 'T' 'Q' 'L']
['P' 'H' 'C' 'N']
['T' 'H' 'N' 'D' 'M' 'W' 'Q' 'B']
['M' 'B' 'R' 'J' 'G' 'S' 'L']
['Z' 'N' 'W' 'G' 'V' 'B' 'R' 'T']
['W' 'G' 'D' 'N' 'P' 'L']

End Position: 

['J']
['N']
['M' 'T' 'W' 'R']
['P' 'G' 'N' 'L' 'N' 'C' 'N' 'L' 'N' 'Q' 'W' 'S']
['L' 'S' 'C']
['G' 'T' 'M' 'W' 'C' 'H' 'D']
['G' 'T' 'R' 'D' 'W' 'N' 'V' 'Z' 'J' 'P' 'L' 'H' 'H' 'W' 'M' 'T' 'D' 'Q'
 'W']
['B' 'N' 'P']
['B' 'B' 'G' 'H' 'D' 'P']

Top Crates



'JNRSCDWPP'

In [410]:
crate_list = [i[i != ' '][::-1] for i in text_array[text_idx, 0:8]]



for crates in crate_list:
    print(crates)
    
crate_move_list = []
for i, move in enumerate(move_list):
    
    if i == 0:
        crate_move_list.append(move_cargo(move[0], move[1], move[2], crate_list))
    else:
        crate_move_list.append(move_cargo(move[0], move[1], move[2], crate_move_list[i-1]))
        
    print(i)
    print(move)
    for crates in crate_move_list[i]:
        print(crates)

[array(['C'], dtype='<U1'),
 array(['M'], dtype='<U1'),
 array(['P', 'D', 'N', 'Z'], dtype='<U1')]

In [399]:

for crates in crate_list:
    print(crates)
    
crate_move_list = []
for i, move in enumerate(move_list):
    
    if i == 0:
        crate_move_list.append(move_cargo(move[0], move[1], move[2], crate_list))
    else:
        crate_move_list.append(move_cargo(move[0], move[1], move[2], crate_move_list[i-1]))
        
    print(i)
    print(move)
    for crates in crate_move_list[i]:
        print(crates)

<ipython-input-399-d558afe75a17>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  test_list =    np.array([['C', 'M'], [], ['P', 'D', 'N']])


['D']
['V']
['H' 'N' 'T' 'W']
['T' 'W' 'D' 'W' 'B' 'H' 'R' 'C' 'T' 'C' 'N' 'Q']
['M' 'G' 'N']
['N' 'L' 'N' 'J' 'P' 'W' 'G']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H' 'T' 'P' 'B' 'W' 'Z' 'N' 'D' 'S' 'W' 'R'
 'C']
['G' 'G' 'P']
['J' 'S' 'M' 'M' 'B' 'L']
0
[6 6 5]
['D']
['V']
['H' 'N' 'T' 'W']
['T' 'W' 'D' 'W' 'B' 'H' 'R' 'C' 'T' 'C' 'N' 'Q']
['M' 'G' 'N' 'G' 'W' 'P' 'J' 'N' 'L']
['N']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H' 'T' 'P' 'B' 'W' 'Z' 'N' 'D' 'S' 'W' 'R'
 'C']
['G' 'G' 'P']
['J' 'S' 'M' 'M' 'B' 'L']
1
[2 5 9]
['D']
['V']
['H' 'N' 'T' 'W']
['T' 'W' 'D' 'W' 'B' 'H' 'R' 'C' 'T' 'C' 'N' 'Q']
['M' 'G' 'N' 'G' 'W' 'P' 'J']
['N']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H' 'T' 'P' 'B' 'W' 'Z' 'N' 'D' 'S' 'W' 'R'
 'C']
['G' 'G' 'P']
['J' 'S' 'M' 'M' 'B' 'L' 'L' 'N']
2
[8 9 1]
['D' 'N' 'L' 'L' 'B' 'M' 'M' 'S' 'J']
['V']
['H' 'N' 'T' 'W']
['T' 'W' 'D' 'W' 'B' 'H' 'R' 'C' 'T' 'C' 'N' 'Q']
['M' 'G' 'N' 'G' 'W' 'P' 'J']
['N']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H' 'T' 'P' 'B' 'W' 'Z' 'N' 'D' 'S' 'W' 'R'
 'C']
['G' 'G' 'P']


[1 9 8]
['V']
['R' 'G' 'N' 'T' 'C' 'L' 'N' 'C' 'T']
[]
['T' 'W' 'D' 'W' 'B' 'H' 'N' 'S' 'J' 'P' 'G' 'N' 'W' 'T' 'C' 'Z' 'W' 'P'
 'J' 'M' 'G' 'D' 'B' 'L' 'M' 'G' 'N' 'N' 'P' 'B' 'H' 'Q' 'S']
['R']
['W' 'M']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H']
['W' 'D']
[]
114
[1 6 3]
['V']
['R' 'G' 'N' 'T' 'C' 'L' 'N' 'C' 'T']
['M']
['T' 'W' 'D' 'W' 'B' 'H' 'N' 'S' 'J' 'P' 'G' 'N' 'W' 'T' 'C' 'Z' 'W' 'P'
 'J' 'M' 'G' 'D' 'B' 'L' 'M' 'G' 'N' 'N' 'P' 'B' 'H' 'Q' 'S']
['R']
['W']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H']
['W' 'D']
[]
115
[26  4  3]
['V']
['R' 'G' 'N' 'T' 'C' 'L' 'N' 'C' 'T']
['M' 'S' 'Q' 'H' 'B' 'P' 'N' 'N' 'G' 'M' 'L' 'B' 'D' 'G' 'M' 'J' 'P' 'W'
 'Z' 'C' 'T' 'W' 'N' 'G' 'P' 'J' 'S']
['T' 'W' 'D' 'W' 'B' 'H' 'N']
['R']
['W']
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'H']
['W' 'D']
[]
116
[1 5 8]
['V']
['R' 'G' 'N' 'T' 'C' 'L' 'N' 'C' 'T']
['M' 'S' 'Q' 'H' 'B' 'P' 'N' 'N' 'G' 'M' 'L' 'B' 'D' 'G' 'M' 'J' 'P' 'W'
 'Z' 'C' 'T' 'W' 'N' 'G' 'P' 'J' 'S']
['T' 'W' 'D' 'W' 'B' 'H' 'N']
[]
['W']
['L' 'Q' 'L' 'N' 'H' 'P' '

['N' 'W' 'N' 'G' 'C']
179
[5 1 3]
[]
[]
['H' 'B' 'D' 'J' 'M' 'G' 'N']
['W' 'W' 'T' 'P' 'B' 'N' 'Z' 'S' 'J']
['P' 'R' 'T' 'T' 'C' 'W']
[]
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'G' 'P' 'W' 'D' 'D' 'B' 'L' 'M' 'G' 'N' 'H'
 'M' 'S' 'W' 'T']
['H' 'R' 'N' 'L' 'C' 'Q' 'V']
['N' 'W' 'N' 'G' 'C']
180
[2 3 4]
[]
[]
['H' 'B' 'D' 'J' 'M']
['W' 'W' 'T' 'P' 'B' 'N' 'Z' 'S' 'J' 'N' 'G']
['P' 'R' 'T' 'T' 'C' 'W']
[]
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'G' 'P' 'W' 'D' 'D' 'B' 'L' 'M' 'G' 'N' 'H'
 'M' 'S' 'W' 'T']
['H' 'R' 'N' 'L' 'C' 'Q' 'V']
['N' 'W' 'N' 'G' 'C']
181
[3 9 5]
[]
[]
['H' 'B' 'D' 'J' 'M']
['W' 'W' 'T' 'P' 'B' 'N' 'Z' 'S' 'J' 'N' 'G']
['P' 'R' 'T' 'T' 'C' 'W' 'C' 'G' 'N']
[]
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'G' 'P' 'W' 'D' 'D' 'B' 'L' 'M' 'G' 'N' 'H'
 'M' 'S' 'W' 'T']
['H' 'R' 'N' 'L' 'C' 'Q' 'V']
['N' 'W']
182
[4 5 2]
[]
['N' 'G' 'C' 'W']
['H' 'B' 'D' 'J' 'M']
['W' 'W' 'T' 'P' 'B' 'N' 'Z' 'S' 'J' 'N' 'G']
['P' 'R' 'T' 'T' 'C']
[]
['L' 'Q' 'L' 'N' 'H' 'P' 'D' 'G' 'P' 'W' 'D' 'D' 'B' 'L' 'M' 'G' 'N' 'H'
 'M' 

 'P' 'P' 'B']
['N' 'W' 'C' 'Q' 'N' 'T' 'G' 'T' 'N']
[]
[]
['C' 'W']
['N' 'J' 'S' 'M' 'T' 'R' 'V' 'P']
['L']
['R' 'H' 'D' 'D' 'D' 'B' 'L' 'M' 'W' 'M' 'J' 'D' 'B' 'H' 'W']
[]
264
[5 2 3]
['Q' 'N' 'L' 'C' 'W' 'S' 'G' 'T' 'Z' 'H' 'N' 'P' 'W' 'G' 'G' 'L' 'N' 'H'
 'P' 'P' 'B']
['N' 'W' 'C' 'Q']
['N' 'T' 'G' 'T' 'N']
[]
['C' 'W']
['N' 'J' 'S' 'M' 'T' 'R' 'V' 'P']
['L']
['R' 'H' 'D' 'D' 'D' 'B' 'L' 'M' 'W' 'M' 'J' 'D' 'B' 'H' 'W']
[]
265
[3 2 4]
['Q' 'N' 'L' 'C' 'W' 'S' 'G' 'T' 'Z' 'H' 'N' 'P' 'W' 'G' 'G' 'L' 'N' 'H'
 'P' 'P' 'B']
['N']
['N' 'T' 'G' 'T' 'N']
['Q' 'C' 'W']
['C' 'W']
['N' 'J' 'S' 'M' 'T' 'R' 'V' 'P']
['L']
['R' 'H' 'D' 'D' 'D' 'B' 'L' 'M' 'W' 'M' 'J' 'D' 'B' 'H' 'W']
[]
266
[20  1  2]
['Q']
['N' 'B' 'P' 'P' 'H' 'N' 'L' 'G' 'G' 'W' 'P' 'N' 'H' 'Z' 'T' 'G' 'S' 'W'
 'C' 'L' 'N']
['N' 'T' 'G' 'T' 'N']
['Q' 'C' 'W']
['C' 'W']
['N' 'J' 'S' 'M' 'T' 'R' 'V' 'P']
['L']
['R' 'H' 'D' 'D' 'D' 'B' 'L' 'M' 'W' 'M' 'J' 'D' 'B' 'H' 'W']
[]
267
[1 1 5]
[]
['N' 'B' 'P' 'P' 'H' 'N' 'L' 'G' 'G' 'W'

 'T' 'H' 'P' 'P' 'C' 'T' 'Z' 'P' 'L']
['B' 'C' 'T' 'D' 'D']
['L' 'M' 'M' 'J' 'N' 'H']
['Q' 'G' 'W' 'T' 'D' 'B']
346
[4 8 4]
[]
['D' 'H' 'R']
['G' 'C' 'W']
['Q' 'G' 'L' 'W' 'W' 'H' 'N' 'J' 'M']
['S']
['N' 'J' 'N' 'W' 'N' 'G' 'W' 'P' 'N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'N'
 'T' 'H' 'P' 'P' 'C' 'T' 'Z' 'P' 'L']
['B' 'C' 'T' 'D' 'D']
['L' 'M']
['Q' 'G' 'W' 'T' 'D' 'B']
347
[3 2 8]
[]
[]
['G' 'C' 'W']
['Q' 'G' 'L' 'W' 'W' 'H' 'N' 'J' 'M']
['S']
['N' 'J' 'N' 'W' 'N' 'G' 'W' 'P' 'N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'N'
 'T' 'H' 'P' 'P' 'C' 'T' 'Z' 'P' 'L']
['B' 'C' 'T' 'D' 'D']
['L' 'M' 'R' 'H' 'D']
['Q' 'G' 'W' 'T' 'D' 'B']
348
[1 7 8]
[]
[]
['G' 'C' 'W']
['Q' 'G' 'L' 'W' 'W' 'H' 'N' 'J' 'M']
['S']
['N' 'J' 'N' 'W' 'N' 'G' 'W' 'P' 'N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'N'
 'T' 'H' 'P' 'P' 'C' 'T' 'Z' 'P' 'L']
['B' 'C' 'T' 'D']
['L' 'M' 'R' 'H' 'D' 'D']
['Q' 'G' 'W' 'T' 'D' 'B']
349
[3 3 9]
[]
[]
[]
['Q' 'G' 'L' 'W' 'W' 'H' 'N' 'J' 'M']
['S']
['N' 'J' 'N' 'W' 'N' 'G' 'W' 'P' 'N' 'V' 'N' 'L' 'M' 

['M']
['S' 'C']
['N' 'W' 'W' 'W' 'N' 'D' 'L' 'P' 'Z' 'T']
[]
['N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'B' 'D' 'T' 'N' 'T' 'H' 'P' 'P']
['N' 'L']
400
[1 4 8]
['G']
['G' 'Q' 'Q' 'C' 'J' 'H' 'N' 'J' 'T' 'W' 'G' 'W' 'P' 'D' 'B' 'R' 'H' 'D']
['G' 'W' 'C' 'M' 'L']
[]
['S' 'C']
['N' 'W' 'W' 'W' 'N' 'D' 'L' 'P' 'Z' 'T']
[]
['N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'B' 'D' 'T' 'N' 'T' 'H' 'P' 'P' 'M']
['N' 'L']
401
[4 6 8]
['G']
['G' 'Q' 'Q' 'C' 'J' 'H' 'N' 'J' 'T' 'W' 'G' 'W' 'P' 'D' 'B' 'R' 'H' 'D']
['G' 'W' 'C' 'M' 'L']
[]
['S' 'C']
['N' 'W' 'W' 'W' 'N' 'D']
[]
['N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'B' 'D' 'T' 'N' 'T' 'H' 'P' 'P' 'M'
 'T' 'Z' 'P' 'L']
['N' 'L']
402
[1 6 9]
['G']
['G' 'Q' 'Q' 'C' 'J' 'H' 'N' 'J' 'T' 'W' 'G' 'W' 'P' 'D' 'B' 'R' 'H' 'D']
['G' 'W' 'C' 'M' 'L']
[]
['S' 'C']
['N' 'W' 'W' 'W' 'N']
[]
['N' 'V' 'N' 'L' 'M' 'B' 'H' 'R' 'S' 'B' 'D' 'T' 'N' 'T' 'H' 'P' 'P' 'M'
 'T' 'Z' 'P' 'L']
['N' 'L' 'D']
403
[2 5 1]
['G' 'C' 'S']
['G' 'Q' 'Q' 'C' 'J' 'H' 'N' 'J' 'T' 'W' 'G' 'W' 'P' 'D' 'B' 'R

['P' 'Z' 'T' 'V' 'N' 'N' 'L' 'D']
['N']
[]
['C' 'M' 'T' 'N' 'J' 'H' 'W' 'G' 'W' 'S' 'L' 'P' 'T' 'C' 'B' 'S' 'W']
['L' 'G' 'M' 'H' 'G']
[]
['N' 'W' 'W' 'D' 'M' 'P' 'L' 'W']
487
[6 2 6]
['P' 'Q' 'Q']
['B' 'C' 'G' 'J' 'N' 'H' 'R' 'B']
['P' 'Z' 'T' 'V' 'N' 'N' 'L' 'D']
['N']
[]
['C' 'M' 'T' 'N' 'J' 'H' 'W' 'G' 'W' 'S' 'L' 'P' 'T' 'C' 'B' 'S' 'W' 'D'
 'R' 'N' 'T' 'H' 'D']
['L' 'G' 'M' 'H' 'G']
[]
['N' 'W' 'W' 'D' 'M' 'P' 'L' 'W']
488
[1 3 1]
['P' 'Q' 'Q' 'D']
['B' 'C' 'G' 'J' 'N' 'H' 'R' 'B']
['P' 'Z' 'T' 'V' 'N' 'N' 'L']
['N']
[]
['C' 'M' 'T' 'N' 'J' 'H' 'W' 'G' 'W' 'S' 'L' 'P' 'T' 'C' 'B' 'S' 'W' 'D'
 'R' 'N' 'T' 'H' 'D']
['L' 'G' 'M' 'H' 'G']
[]
['N' 'W' 'W' 'D' 'M' 'P' 'L' 'W']
489
[1 4 1]
['P' 'Q' 'Q' 'D' 'N']
['B' 'C' 'G' 'J' 'N' 'H' 'R' 'B']
['P' 'Z' 'T' 'V' 'N' 'N' 'L']
[]
[]
['C' 'M' 'T' 'N' 'J' 'H' 'W' 'G' 'W' 'S' 'L' 'P' 'T' 'C' 'B' 'S' 'W' 'D'
 'R' 'N' 'T' 'H' 'D']
['L' 'G' 'M' 'H' 'G']
[]
['N' 'W' 'W' 'D' 'M' 'P' 'L' 'W']
490
[4 6 2]
['P' 'Q' 'Q' 'D' 'N']
['B' 'C' 'G' 'J' 'N' '