### Move Knot Function

In [38]:

import numpy as np

# Initialize Grid
grid = np.repeat(None, 60).reshape(2, 5, 6)
grid[0, 4, 0] = 'H'
grid[1, 4, 0] = 'T'

print(grid)

def move_heads(mat, direction ):

    # mat = matrix/grid 
    
    # Determine x/y direction/sign based on direction input
    if direction == 'U':
        direct_xy = 1
        direct_sign = -1
    elif direction == 'D':
        direct_xy = 1
        direct_sign = 1
    elif direction == 'L':
        direct_xy = 2
        direct_sign = -1
    elif direction == 'R':
        direct_xy = 2
        direct_sign = 1
     
    # Find Current Position
    cur_pos= np.where(mat == 'H')
    
    # Calculate new (potential) position
    new_pos =  cur_pos[direct_xy][0] + direct_sign
    
          
    # Return Same Matrix if New Heads Position is Outof Pounds
    
    if (new_pos < 0) | (new_pos +1 > mat.shape[direct_xy]):
        print('Error: Out of Bounds')
        return(mat)
    
    else:

        # Moveaway from current position
        mat[cur_pos] = None

        # Set New Position for Heads
        cur_pos[direct_xy][0] = new_pos

        # move Tails to New Position
        mat[cur_pos] = 'H'


        return(mat)
    
    
move_heads(grid, 'R')
#grid.shape  

[[[None None None None None None]
  [None None None None None None]
  [None None None None None None]
  [None None None None None None]
  ['H' None None None None None]]

 [[None None None None None None]
  [None None None None None None]
  [None None None None None None]
  [None None None None None None]
  ['T' None None None None None]]]


array([[[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, 'H', None, None, None, None]],

       [[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        ['T', None, None, None, None, None]]], dtype=object)

In [15]:
import numpy as np

# Initialize Grid
grid = np.repeat(None, 60).reshape(2, 5, 6)
grid[0, 4, 0] = 'H'
grid[1, 4, 0] = 'T'

print(grid)



move_heads(grid, R')

move_heads(grid, 'U')

[[[None None None None None None]
  [None None None None None None]
  [None None None None None None]
  [None None None None None None]
  ['H' None None None None None]]

 [[None None None None None None]
  [None None None None None None]
  [None None None None None None]
  [None None None None None None]
  ['T' None None None None None]]]


array([[[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, 'H', None, None, None, None],
        [None, None, None, None, None, None]],

       [[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        ['T', None, None, None, None, None]]], dtype=object)

### move_knots ( ) function

In [99]:
def move_knots(mat, direction, steps):
    
    for i in range(1,steps+1):
        move_heads(mat, direction)
        #print(grid)
        
        
import numpy as np

# Initialize Grid
grid = np.repeat(None, 60).reshape(2, 5, 6)
grid[0, 4, 0] = 'H'
grid[1, 4, 0] = 'T'


move_knots(grid, 'R', 4)

### move_tails( ) function

In [78]:
# Initialize Grid
grid = np.repeat(None, 60).reshape(2, 5, 6)
grid[0, 4, 0] = 'H'
grid[1, 4, 0] = 'T'

# Definf follow_head

def move_tails(grid):
    
    # Compare Positions
    vert = np.where(grid[0] == 'H')[0][0] - np.where(grid[1] == 'T')[0][0]
    horiz =  np.where(grid[0] == 'H')[1][0] - np.where(grid[1] == 'T')[1][0]
    
    #print([horiz, vert])

 
    # Tails Moves Right & Up
    if ((horiz >= 1) & (vert <= - 2)) | ((horiz >= 2) & (vert <= -1)):
        
        #print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
        
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[2][0] = cur_pos_T[2][0] +  1
        cur_pos_T[1][0] = cur_pos_T[1][0] + -1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
        
    # Tails Moves Left and Down
    elif ((horiz <= -1) & (vert >= 2)) | ((horiz <= -2) & (vert >= 1)):
        
                
        #print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
        
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[2][0] = cur_pos_T[2][0] + -1
        cur_pos_T[1][0] = cur_pos_T[1][0] +  1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
        
    
        
    # Tails Moves Up and Left
    elif ((horiz <= -2) & (vert <= -1)) | ((horiz <= -1) & (vert <= -2)):
        
                
        #print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
        
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[2][0] = cur_pos_T[2][0] + -1
        cur_pos_T[1][0] = cur_pos_T[1][0] + -1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
        
    
    # Tails Moves Down & Right
    elif ((horiz >= 2) & (vert >= 1)) | ((horiz >= 1) & (vert >= 2)):
        
                
       # print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
        
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[2][0] = cur_pos_T[2][0] + 1
        cur_pos_T[1][0] = cur_pos_T[1][0] + 1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
    
    
    # Tails Moves Down
    elif vert >= 2:
            
       # print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
        
        
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[1][0] = cur_pos_T[1][0] + -1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
    
        
    # Tails Moves Up
    elif vert <= -2:
            
        #print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
        
        
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[1][0] = cur_pos_T[1][0] + -1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
    
        
    # Tails Moves Right 
    elif horiz >= 2:
        
        #print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')
 
        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[2][0] = cur_pos_T[2][0] + 1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
        
    # Talils Moves Left
    elif horiz <= -2:
        
        #print('Move')
        
        # Find Current Position of Tails
        cur_pos_T = np.where(grid == 'T')

        # Move Tails away from current position
        grid[cur_pos_T] = None
        
        # Set New Position for Tails
        cur_pos_T[2][0] = cur_pos_T[2][0] - 1
        
        # move Tails to New Position
        grid[cur_pos_T] = 'T'
        
    return(grid)
        

In [60]:
# Initialize Grid
grid = np.repeat(None, 60).reshape(2, 5, 6)
grid[0, 4, 0] = 'H'
grid[1, 4, 0] = 'T'
grid


def move_knots(mat, direction, steps):
    
    for i in range(1,steps+1):
        move_heads(mat, direction)
        print(grid)
        
        

move_heads(grid, 'R')
move_heads(grid, 'R')
move_tails(grid)
move_heads(grid, 'R')
move_tails(grid)
move_heads(grid, 'R')
move_tails(grid)
move_heads(grid, 'U')
move_heads(grid, 'U')
move_tails(grid)

[2, 0]
[2, 0]
[2, 0]
[1, -2]


array([[[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, 'H', None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None]],

       [[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, 'T', None],
        [None, None, None, None, None, None]]], dtype=object)

In [109]:
# Initialize Grid
grid = np.repeat(None, 60).reshape(2, 5, 6)
grid[0, 4, 0] = 'H'
grid[1, 4, 0] = 'T'

grid_track = np.zeros(30).reshape(1, 5, 6)


def move_knots(mat, direction, steps, track):
    
    for i in range(1,steps+1):
        
        move_heads(mat, direction)
        move_tails(mat)
        
        # Note here just add 1 instead of multiplying 
        track = track + (grid[1,:, :] == 'T')*1

    return(track)


grid_track = move_knots(grid, 'R', 4, grid_track)
grid_track = move_knots(grid, 'U', 4, grid_track)
grid_track = move_knots(grid, 'L', 3, grid_track)
grid_track = move_knots(grid, 'D', 1, grid_track)
grid_track = move_knots(grid, 'R', 4, grid_track)
grid_track = move_knots(grid, 'D', 1, grid_track)
grid_track = move_knots(grid, 'L', 5, grid_track)
grid_track = move_knots(grid, 'R', 2, grid_track)
print(grid_track)
print(1*(grid_track > 0))
print(np.sum(grid_track > 0))

[[[0. 0. 4. 1. 0. 0.]
  [0. 0. 0. 1. 6. 0.]
  [0. 3. 1. 1. 1. 0.]
  [0. 0. 0. 0. 1. 0.]
  [1. 1. 1. 2. 0. 0.]]]
[[[0 0 1 1 0 0]
  [0 0 0 1 1 0]
  [0 1 1 1 1 0]
  [0 0 0 0 1 0]
  [1 1 1 1 0 0]]]
13


# Part 1

In [106]:
with open('data/input_2022-12-09.txt') as f:
    lines = [line.strip('\n').split(' ') for line in f.readlines()]
    
text = [[x[0], int(x[1])] for x in lines]
text[0:4]

[['D', 2], ['U', 2], ['L', 2], ['D', 2]]

In [123]:
# Initialize Grid
grid = np.repeat(None, 1280000).reshape(2, 800, 800)
grid[0, 400, 400] = 'H'
grid[1, 400, 400] = 'T'

grid_track = np.zeros(640000, dtype = int).reshape(1, 800, 800)
grid_track[400, 400] = int(1)

for i,steps in enumerate(text):
    
    if i % 100 == 0:
        print(i)
        
    grid_track = move_knots(grid, steps[0], steps[1], grid_track)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900


In [124]:
print(np.sum(grid_track > 0))

9326


In [141]:
grid_track.shape

for row in grid_track[0, 200:240, 200:240]:
    print(row)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 